### ISSUE TITLE
[Feature Request] Share Text String without Sending a File

### ISSUE THREAD

**Issue by daOrangePeeler** [mat-sz/filedrop-web#10]
First of all, thanks for such a great project! It seems really well done and has worked very well for me.

Is there anyway that a feature could be added where you could just send text without a file? I'm thinking something like Snapdrop's right-click (or long-press on mobile) to send a message. I'm not sure how it would work exactly once the message is received, but even just being able to tap or click on the message to copy the text would be great.

If you don't feel this would be worth the effort I totally understand. Thanks again!

**Comment by mat-sz** [comment]
Took me a while to create a understandable UX flow for this, and what I came up with is a simple chat system with a "Copy to clipboard" button. The feature should be now live in production.

The chat is only accessible to clients that support the Web Crypto API. All messages are end-to-end encrypted.

![image](https://user-images.githubusercontent.com/57893590/103550583-696b2080-4ea9-11eb-9c0d-0d5bacfe1ab0.png)

**Comment by daOrangePeeler** [comment]
Wow, that's a really good way to implement it. Thanks!
