### ISSUE TITLE
drop.lol unable to connect on any browser

### ISSUE THREAD

**Issue by Phantop** [mat-sz/filedrop-web#11]
As the title says, any attempt to visit https://drop.lol/ gets stuck on a screen that just say "Connecting...", as shown in the screenshot below.
![Screenshot from 2021-04-08 23-35-48](https://user-images.githubusercontent.com/11746629/114124772-2911a900-98c3-11eb-8f70-1a20b3bef763.png)

**Comment by mat-sz** [comment]
@Phantop Thank you for the report, the issue has been resolved.
