### ISSUE TITLE
No file picker

### ISSUE THREAD

**Issue by sid-code** [mat-sz/filedrop-web#2]
It is impossible (or very not obvious how) to use this service without a graphical file manager. Most websites usually have a "Drag file here or click to choose one."

**Comment by mat-sz** [comment]
![image](https://user-images.githubusercontent.com/57893590/74090524-8c7c2d00-4aac-11ea-9a4a-a759e8bec98d.png)

Please read the text in the user interface.

**Comment by sid-code** [comment]
I clicked on a tile. Nothing happened. Remember, if the user doesn't understand your instructions, it's your fault no matter what. I'm not even a potential user of this service, was just trying to help. Good luck.

**Comment by mat-sz** [comment]
> I clicked on a tile. Nothing happened.
Have you clicked on the "You" tile on any other tile? If it was the "any other tile" and nothing showed up then it is a bug (please let me know which browser are you using, under which OS and all the other relevant information), but you should've specified that in your initial report.

> Remember, if the user doesn't understand your instructions, it's your fault no matter what.
I wouldn't necessarily agree with that. Even with the best instructions (mine aren't exactly clear, but should be understandable after a careful read) there is someone who won't be able to figure out what to do.

It could also be argued - if the developer doesn't understand your bug report, it's your fault no matter what.
