### ISSUE TITLE
some issue related to "localNetworkNames" in the main.xxx.js file

### ISSUE THREAD

**Issue by msrl2000** [mat-sz/filedrop-web#20]
Hi 
While trying to run on Docker, i am getting an error in the browser console:
---------------------
ypeError: Cannot read properties of undefined (reading 'filter')
    at main.cc1ec017.js:2:255383
    at e (main.cc1ec017.js:2:154208)
    at main.cc1ec017.js:2:154413
    at Object.useSyncExternalStore (main.cc1ec017.js:2:78270)
    at t.useSyncExternalStore (main.cc1ec017.js:2:145742)
    at t.useSyncExternalStoreWithSelector (main.cc1ec017.js:2:154483)
    at main.cc1ec017.js:2:156142
    at Fo (main.cc1ec017.js:2:255357)
    at ki (main.cc1ec017.js:2:71227)
    at xs (main.cc1ec017.js:2:128467)
dl @ main.cc1ec017.js:2
n.callback @ main.cc1ec017.js:2
Fa @ main.cc1ec017.js:2
ws @ main.cc1ec017.js:2
bs @ main.cc1ec017.js:2
ys @ main.cc1ec017.js:2
(anonymous) @ main.cc1ec017.js:2
Su @ main.cc1ec017.js:2
ou @ main.cc1ec017.js:2
E @ main.cc1ec017.js:2
R @ main.cc1ec017.js:2
main.cc1ec017.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at main.cc1ec017.js:2:255383
    at e (main.cc1ec017.js:2:154208)
    at main.cc1ec017.js:2:154413
    at Object.useSyncExternalStore (main.cc1ec017.js:2:78270)
    at t.useSyncExternalStore (main.cc1ec017.js:2:145742)
    at t.useSyncExternalStoreWithSelector (main.cc1ec017.js:2:154483)
    at main.cc1ec017.js:2:156142
    at Fo (main.cc1ec017.js:2:255357)
    at ki (main.cc1ec017.js:2:71227)
    at xs (main.cc1ec017.js:2:128467)
-------------------

Screen is Black an nothings appeares.
while trying to point to the error in the main.js, it jumps to this section:
--------------
e.localNetworkNames.filter((t=>t!==e.networkName))));return 0===n.length?null:(0,We.jsxs)
-------------------

i am not sure, but if i am searchinf for "NetworkNames" in the code, it is point me to out to:
filedrop-web\src\sections\OtherNetworks\index.tsx
ChatGPT [  ;)  ] says it is related to the setion:
-----
 const localNetworkNames = useSelector((store: StateType) =>
    store.localNetworkNames.filter(name => name !== store.networkName)
  );

  if (localNetworkNames.length === 0) {
    return null;
  }

--------------
triyng to use chatGPT advise replacing this with another code,
------------------
const localNetworkNames = useSelector((store: StateType) => {
  if (!store.localNetworkNames) return [];
  return store.localNetworkNames.filter(name => name !== store.networkName);
});
-----------------

 "resolve" the issue but created another one, the website loded with no "errors" in the console, but nothing worked acctually.

Kindly please advise.
best regards.

**Comment by mat-sz** [comment]
The backend submodule is out of date, please update your submodules.

```
git submodule update --remote --recursive
```

**Comment by msrl2000** [comment]
I reclone the whole project (last commit included) + update the submodels as suggested.
now the docker it's runing without errors in the console, but not working.
attached screenshot:
![image](https://user-images.githubusercontent.com/86884058/215638088-6418201c-545f-467b-96c9-322404f3f9b9.png)
