### ISSUE TITLE
The backend submodule is out of date, please update your submodules.

### ISSUE THREAD

**Issue by msrl2000** [mat-sz/filedrop-web#21]
The backend submodule is out of date, please update your submodules.

```
git submodule update --remote --recursive
```

_Originally posted by @mat-sz in https://github.com/mat-sz/filedrop-web/issues/20#issuecomment-1408991327_
            

I reclone the whole project (last commit included) + update the submodels as suggested.
now the docker it's runing without errors in the console, but not working.
attached screenshot:
![image](https://user-images.githubusercontent.com/86884058/215638672-f3157552-8c4f-4cab-855a-83a805f01f28.png)

**Comment by mat-sz** [comment]
@msrl2000 This looks like a language file issue, I'm unable to replicate it though so I'm closing this until more details are provided.
