### ISSUE TITLE
Tyles are not focusable

### ISSUE THREAD

**Issue by sukiletxe** [mat-sz/filedrop-web#3]
First of all, thanks for this awesome project! It works great, having done a quick and dirty test to transfer a file from my PC to iOS.

However, I am finding difficulties with the tyle system. I am totally blind, and I use a [screen reader](https://en.wikipedia.org/wiki/Screen_reader) to access this PC and my phone (they come in tablets, some TVs, etc.). In Mac and iOS this software is called [VoiceOver](https://www.apple.com/accessibility/) (you can enable it in settings or in VoiceOver utility in Mac), in Linux [Orca](https://help.gnome.org/users/orca/stable/introduction.html.en), and in Windows there are several alternatives (I've heard [Narrator](https://en.wikipedia.org/wiki/Microsoft_Narrator) is pretty good in Windows 10, but I use another, called [NVDA](https://www.nvaccess.org), which is also free).

The problem I'm having is that tyles are not accessible. Instead of using a native file picker (the ones where a browse button is shown) you use an alternative which is not focussable, meaning that, in iOS for example, the screen reader cannot focus it (on Windows you can press enter on it but you must know what you are looking for). I honestly don't know how to improve this, but googling "accessible file picker" gives some interesting results. Plus, native file pickers do work (the ones in many pages, like [conversion-tool](https://www.conversion-tool.com/) do work properly.

**Comment by mat-sz** [comment]
Thank you very much for your feedback.

I can reproduce the issue, this behavior is not intended (it used to work properly, but I must've broken that), I will see what can be done and I'll update you when the issue is resolved.

**Comment by sukiletxe** [comment]
Thanks very much, ping me if you need testing. Unfortunately I don't have any other gadget to test it on, apart from Windows and iOS.
Oh, and this file picker on GitHub also works for reference ;) .

**Comment by mat-sz** [comment]
I have identified the issue, fixed it (tested with VoiceOver since it's on my MacBook) and deployed the fixed build to production. It should be resolved now, but depending on your browser's cache it may take up to 72 hours.

Let me know when it's resolved.

**Comment by sukiletxe** [comment]
Tested on iOS 13.3.1 and Windows 10 with NVDA and Firefox (files went both ways), works like a charm. Thank you very much, that was really fast!
