### ISSUE TITLE
Self-Hosted Setup / Docker support

### ISSUE THREAD

**Issue by nikeee** [mat-sz/filedrop-web#4]
Is there a document that outlines how to self-host this service?

I've seen [filedrop-web](https://github.com/mat-sz/filedrop-web) and [filedrop-ws](https://github.com/mat-sz/filedrop-ws). Is this everything required?

Are you open to PRs adding Dockerfiles providing easier setup?

**Comment by mat-sz** [comment]
I had Docker support planned, so all PRs are welcome.

I agree that this project needs more documentation, -ws and -web are enough to run an instance, the only external software that is optional is coturn - which is used on the public version for NAT traversal. The README file on the filedrop-ws project mentions the TURN configuration.

**Comment by petrk94** [comment]
How to install and run it on own domain?

**Comment by mat-sz** [comment]
@petrk94 

First you need to clone, build and run [filedrop-ws](https://github.com/mat-sz/filedrop-ws) and a TURN server (like [coturn](https://github.com/coturn/coturn), read the README in filedrop-ws for more information on configuration.

Then you need to clone this project, point it to the WebSockets backend (filedrop-ws) (in .env.local), build it and place it on some static file server (I use nginx for that). I also use nginx to proxy the back end through it. [Here's a guide on how to achieve that.](https://www.nginx.com/blog/websocket-nginx/)

**Comment by petrk94** [comment]
@mat-sz ah okay, so a websocket server is additionally required. I thought it will work without.

**Comment by mat-sz** [comment]
@petrk94 

filedrop-ws is used to provide information about the current network, coordinate WebRTC offers/answers, provide WebRTC configuration and protect user privacy (until the transfer is started).

**Comment by mat-sz** [comment]
@nikeee @petrk94 @NoverNobida

I've updated the README with installation instructions and created a repo with docker-compose configuration - [filedrop-docker](https://github.com/mat-sz/filedrop-docker). This should provide you with more insight on how the production environment is set up.
