### ISSUE TITLE
Implement Web Share API

### ISSUE THREAD

**Issue by coreyworrell** [mat-sz/filedrop-web#5]
Possible idea. This would allow users, for example, to pick a photo from their native photos app, click the share button and have drop.lol show up as an option to share to.

Example: https://justmarkup.com/articles/2020-02-11-share-images-to-your-website/

**Comment by mat-sz** [comment]
While this is a great idea, unfortunately filedrop-web/filedrop-ws doesn't have any way to handle files on the back end, filedrop-ws only has a WebSocket server.

I really wish I could support this API, but I don't want to handle any kind of file data unencrypted on my server.
