### ISSUE TITLE
[Request] - Bulk upload support

### ISSUE THREAD

**Issue by heretique** [mat-sz/filedrop-web#6]
Hi,
thanks for this piece of software, I used Sharedrop.io for a long time but stumbled upon yours recently and started using it frequently. It seems to have a similar issue (well not necessarily and issue, more of a shortcoming) with Sharedrop and that is that it doesn't seem to support sending multiple files at once (maybe I'm wrong).
I think having bulk upload support would be a great feature for it.

Best!

**Comment by mat-sz** [comment]
As far as I can see it, selecting multiple files at once is possible, but each file will get its own separate transfer. What is the platform you're using and what is the expected result?

**Comment by heretique** [comment]
I want to transfer multiple files from Android to Windows. I open drop.lol on both of then (browser is Firefox) and here are the options:
 - if I press the "+" button and select only one file from Android everything works fine (I get on android side a new list element with the name of the file, the icon for upload and a "cancel" button and on Windows side, the name of the file, download icon and "Accept" & "Reject" buttons.

![Screenshot_20200310-121304](https://user-images.githubusercontent.com/139596/76304449-1990ec80-62cc-11ea-9e3b-138afdbad32b.png)
![single_file](https://user-images.githubusercontent.com/139596/76302511-ccf7e200-62c8-11ea-96a1-6b94de903d9d.jpg)
 - if I select multiple files on Android after pressing the "+" button, I get only one upload element in drop.lol on Android side, but the filename is none of those selected and I don't get anything else on Windows side.

![Screenshot_20200310-121817](https://user-images.githubusercontent.com/139596/76304523-30374380-62cc-11ea-9893-aa57bf12ce22.png)
![Screenshot_20200310-121844](https://user-images.githubusercontent.com/139596/76304534-34636100-62cc-11ea-92a3-0cef05b8705e.png)

**Comment by mat-sz** [comment]
Unfortunately, it looks like a Firefox issue to me. Seems to work well on Chrome with latest Android. I'll try to look for a solution, but I cannot guarantee anything at this stage.

Desktop Firefox has no such issues and that makes debugging this harder.

**Comment by mat-sz** [comment]
Unfortunately I have failed to resolve the problem with Android Firefox, if something changes I will reopen this issue.
