### ISSUE TITLE
Two minor issues with mobile browsers

### ISSUE THREAD

**Issue by NoverNobida** [mat-sz/filedrop-web#7]
There are two minor issues with mobile browsers([kiwi browser](https://github.com/kiwibrowser/android) and firefox). One is that the transfer from the computer to the phone is fast, but the transfer from the phone to the computer is very slow. The second is that there are some problems with the transmission speed display on the mobile browser.
![Screenshot_Kiwi_Browser_20200325-203753](https://user-images.githubusercontent.com/46912250/77538318-7d293580-6eda-11ea-90bd-979a69576a2e.png)

**Comment by mat-sz** [comment]
Hello,

> One is that the transfer from the computer to the phone is fast, but the transfer from the phone to the computer is very slow.

This is actually caused by privacy protections in those browsers. Like Safari, Kiwi and Firefox hide local candidates for WebRTC when constructing an offer (createOffer). This results in one-way bottleneck.

> The second is that there are some problems with the transmission speed display on the mobile browser.

I can fix this one, as opposed to the above one. Thank you for reporting this.

**Comment by NoverNobida** [comment]
It would be better if there is a document to depoly. Maybe TypeScript is difficult for me.  @mat-sz

**Comment by mat-sz** [comment]
I will be adding Docker support myself since the author of #4 didn't reply. I also plan on adding Prettier to enforce some formatting standards, so if you're interested in contributing please wait until that happens.

**Comment by NoverNobida** [comment]
@mat-sz  Thanks!

**Comment by mat-sz** [comment]
I have fixed the progress bar issue and deployed the fix to the public instance (https://drop.lol). Please let me know if your issue is resolved.

For Docker-related updates please follow #4.

**Comment by NoverNobida** [comment]
Yes, it was resolved.
