### ISSUE TITLE
[Feature request] File previews

### ISSUE THREAD

**Issue by RomeSilvanus** [mat-sz/filedrop-web#8]
Really neat project.

Though would it be possible for multimedia files (or at least for images) to have the sending device generate a small preview (that maybe can replace the generic file type icon)?
It's a feature I really miss from other services such as sharedrop, but it would be a very nice to have feature to be actually able to see what it is before you download.

**Comment by mat-sz** [comment]
I'll take a look at this, I actually have my own library for generation of image thumbnails, so at least for images I could handle that.

**Comment by mat-sz** [comment]
@RomeSilvanus I've implemented file previews for image files, they should be live in production as of now.

**Comment by RomeSilvanus** [comment]
That's great, works pretty nice too !

Thanks !
