### ISSUE TITLE
[Feature suggestion] Save all

### ISSUE THREAD

**Issue by zakyum** [mat-sz/filedrop-web#9]
First off, thank you for creating this amazing open source and privacy friendly file sharing platform! Stumbled upon it on HackerNews and must say it's really as good as how other users described it. Personally, way better and easier to use than DropBox and co!

The only thing which might be missing would be a "Save all" button (or something similar?). At least when sharing photos with my friends they note that it's cumbersome to click accept on all photos. Especially on a mobile device...

But it's nothing mayor, just a small suggestion if you ever wonder what to add as a new feature. I'm already glad and happy with the current version! Keep it up mate and have a nice day 😄

**Comment by mat-sz** [comment]
Good idea! Give me an hour.

**Comment by mat-sz** [comment]
The feature is now ready and should be available in production right now.

![image](https://user-images.githubusercontent.com/57893590/103153587-e1db2e80-4791-11eb-8062-bb0fbb086979.png)

**Comment by zakyum** [comment]
Wow, this was super fast, thank you very much! 😄
